services:
# WRITE
    medzoner.contact.controller:
        class: 'Medzoner\GlobalBundle\Controller\ContactController'
        public: 'false'
        arguments:
            - '@request_stack'
            - '@templating'
            - '@form.factory'
            - '@session'
            - '@router'
            - '@command_bus'

    medzoner.contact.form:
        class: 'Medzoner\GlobalBundle\Form\RegistrationType'
        public: 'false'
        tags:
            - { name: 'form.type', alias: 'contact' }

    medzoner.contact.odm.repository:
        class: 'Medzoner\GlobalBundle\Repository\ContactRepositoryODM'
        public: 'false'
        arguments:
            - '@doctrine_mongodb.odm.document_manager'

    medzoner.contact.orm.repository:
        class: 'Medzoner\GlobalBundle\Repository\ContactRepositoryORM'
        public: 'false'
        factory: ['@doctrine', 'getRepository']
        arguments:
            - 'Medzoner\GlobalBundle\Entity\Contact'

    medzoner.contact.register_contact.commandhandler:
        class: 'Medzoner\Domain\CommandHandler\RegisterContactCommandHandler'
        public: 'false'
        arguments:
            - '@medzoner.contact.orm.repository'
            - '@event_bus'
            - '@jms_serializer'
        tags:
            - { name: 'command_handler', handles: 'Medzoner\Domain\Command\RegisterContactCommand' }

# READ
    medzoner.contact.registered_contact.eventhandler:
        class: 'Medzoner\Domain\EventHandler\RegisteredContactEventHandler'
        public: 'false'
        arguments:
            - '@medzoner.contact.send_contact.service'
            - '@medzoner.contact.odm.repository'
        tags:
            - { name: 'event_subscriber', subscribes_to: 'registered_contact_event' }
            # dev env:
            #- { name: 'asynchronous_event_subscriber', subscribes_to: 'registered_contact_event' }

    medzoner.contact.send_contact.service:
        class: 'Medzoner\GlobalBundle\Services\SendContactService'
        public: 'false'
        arguments:
            - '@templating'
            - '@mailer'