services:
# WRITE
    Medzoner\GlobalBundle\Controller\ContactController:
        public: true
        arguments:
            - '@request_stack'
            - '@twig'
            - '@form.factory'
            - '@session'
            - '@router'
            - '@command_bus'

    medzoner.contact.form:
        class: 'Medzoner\GlobalBundle\Form\RegistrationType'
        public: 'false'
        tags:
            - { name: 'form.type', alias: 'contact' }


    medzoner.contact.orm.repository:
        class: 'Medzoner\GlobalBundle\Repository\ContactRepositoryORM'
        public: 'false'
        factory: ['@doctrine', 'getRepository']
        arguments:
            - 'Medzoner\GlobalBundle\Entity\Contact'

    medzoner.contact.register_contact.commandhandler:
        class: 'Medzoner\Domain\CommandHandler\RegisterContactCommandHandler'
        public: 'false'
        arguments:
            - '@medzoner.contact.orm.repository'
            - '@event_bus'
            - '@jms_serializer'
        tags:
            - { name: 'asynchronous_command_handler', handles: 'Medzoner\Domain\Command\RegisterContactCommand' }

    medzoner.contact.register_contact.eventhandler:
        class: 'Medzoner\Domain\EventHandler\RegisteredContactEventHandler'
        public: 'false'
        arguments:
            - '@medzoner.contact.send_contact.service'
        tags:
            - { name: 'asynchronous_event_subscriber', subscribes_to: 'Medzoner\Domain\Event\RegisteredContactEvent' }

    medzoner.contact.send_contact.service:
        class: 'Medzoner\GlobalBundle\Services\SendContactService'
        public: 'false'
        arguments:
            - '@twig'
            - '@mailer'