services:
  Medzoner\GlobalBundle\Controller\IndexController:
    public: true
    bind:
        $request: '@request_stack'
        $templating: '@templating'
        #- '@fos_http_cache.handler.tag_handler'
        #- '@fos_http_cache.cache_manager'
