services:
  medzoner.jobboard.service:
    class: 'Medzoner\GlobalBundle\Services\JobBoardService'
    arguments:
        - '@medzoner.jobboard.provider'

  medzoner.jobboard.controller:
    class: 'Medzoner\GlobalBundle\Controller\TechnosController'
    arguments:
        - '@request_stack'
        - '@templating'
        - '@medzoner.jobboard.queryhandler'

  medzoner.jobboard.model:
    class: 'Medzoner\GlobalBundle\Model\JobBoard\JobBoard'

  medzoner.jobboard.queryhandler:
    class: 'Medzoner\Domain\QueryHandler\ListJobBoardQueryHandler'
    arguments:
        - '@medzoner.jobboard.service'

  medzoner.jobboard.content.model:
    class: 'Medzoner\GlobalBundle\Model\JobBoard\JobBoardContent'

  medzoner.jobboard.provider:
    class: 'Medzoner\GlobalBundle\Provider\JobBoard\JobBoardProvider'