services:
  medzoner.jobboard.service:
    class: 'Medzoner\GlobalBundle\Services\JobBoardService'
    arguments:
        - '@medzoner.jobboard.provider'

  Medzoner\GlobalBundle\Controller\TechnosController:
    public: true
    bind:
        $request: '@request_stack'
        $templating: '@templating'
        $jobBoardQueryHandler: '@medzoner.jobboard.queryhandler'

  medzoner.jobboard.model:
    class: 'Medzoner\GlobalBundle\Model\JobBoard\JobBoard'

  medzoner.jobboard.queryhandler:
    class: 'Medzoner\Domain\QueryHandler\ListJobBoardQueryHandler'
    arguments:
        - '@medzoner.jobboard.service'

  medzoner.jobboard.content.model:
    class: 'Medzoner\GlobalBundle\Model\JobBoard\JobBoardContent'

  medzoner.jobboard.provider:
    class: 'Medzoner\GlobalBundle\Provider\JobBoard\JobBoardProvider'