monolog:
    handlers:
        main:
            type:             stream
            path:             %kernel.logs_dir%/%kernel.environment%.log
            level:            debug
        firephp:
            type:             firephp
            level:            info
        chromephp:
            type:             chromephp
            level:            info
        console:
            type:             console
            bubble:           false
            verbosity_levels:
                VERBOSITY_VERBOSE:      INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels:         ["!doctrine"]
        console_very_verbose:
            type:             console
            bubble:           false
            verbosity_levels:
                VERBOSITY_VERBOSE:      NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG:        DEBUG
            channels:         ["doctrine"]

        swift:
          type: swift_mailer
          from_email: %monolog_mail%
          to_email: %monolog_mail%
          subject: "[medzoner.com %branch%] An Error Occurred!"
          level: critical

      elasticsearch:
            type: elasticsearch
            index: medzoner-%branch%
            elasticsearch:
              host: elastic.medzoner.com
              port: 9200
            level: critical