# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    #encryption: "tls"
    #port:       "587"
    #encryption: "%mailer_encryption%"
    #port:       "%mailer_port%"
    spool:
        type: 'file'
        path: '%kernel.root_dir%/spool'
