fos_elastica:
    clients:
        default: { host: '%elastica_host%', port: '%elastica_port%' }
    indexes:
        app:
            index_name: 'app_%kernel.environment%'
            settings:
                index:
                    analysis:
                        analyzer:
                            autocomplete_analyzer:
                                type: 'custom'
                                tokenizer: 'autocomplete_tokenizer'
                                filter: ['lowercase', 'asciifolding']
                        tokenizer:
                            autocomplete_tokenizer:
                                type: 'nGram'
                                min_gram: 3
                                max_gram: 20
            types:
                contact:
                    mappings:
                        id:
                            type: 'integer'
                        email :
                            type : 'string'
                        name :
                            type : 'string'
                    properties:
                        email: ~
                        name: ~
                    persistence:
                        identifier: 'id'
                        driver: 'orm'
                        model: 'Medzoner\GlobalBundle\Entity\Contact'
                        provider: ~
                        finder: ~
                        listener: ~
                        repository: 'Medzoner\GlobalBundle\Repository\ContactRepositoryElastica'
