jms_serializer:
    metadata:
        auto_detection: true
        directories:
            Domain:
                path: "@MedzonerGlobalBundle/Resources/serializer/domain"
                namespace_prefix: "Medzoner\\Domain"
