# app/config/bundles/jms.yml

# JMS\SerializerBundle\JMSSerializerBundle configuration
jms_serializer:
    metadata:
        auto_detection: true

        # Declare the specific SERIALIZER for domain
        directories:
            Domain:
                path: "@MedzonerGlobalBundle/Resources/serializer/domain"
                namespace_prefix: "Medzoner\\Domain"
