# Redis
snc_redis:
    clients:
        default:
            type: 'predis'
            alias: 'cache'
            dsn: '%env(string:redis_client_default_dsn)%'
            options:
                prefix : "medzoner:cache:"
                profile: 3.2
                connection_timeout: '%env(string:redis_connection_timeout)%'
                read_write_timeout: '%env(string:redis_read_write_timeout)%'

        mailer:
            type: 'predis'
            alias: 'mailer'
            dsn: '%env(string:redis_client_default_dsn)%'
            options:
                prefix : "medzoner:mailer:"
                profile: 3.2
                connection_timeout: '%env(string:redis_connection_timeout)%'
                read_write_timeout: '%env(string:redis_read_write_timeout)%'

        log:
            type: 'predis'
            alias: 'monolog'
            dsn: '%env(string:redis_client_default_dsn)%'
            logging: false
            options:
                prefix : "medzoner:monolog:"
                connection_persistent: true

    monolog:
        client: 'monolog'
        key: 'monolog'

    swiftmailer:
        client: 'mailer'
        key: 'swiftmailer'
