pipeline:
    docker:
        image: php:7.1
        commands:
          - sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
          - sudo apt-get install -y --force-yes nginx nodejs curl
          - ./bin/phpunit -c app
          - npm install && npm install -g bower karma gulp && gulp && composer install -n --no-dev --optimize-autoloader --no-progress && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && bash deploy.sh 1.0

    deploy:
        image: quay.io/honestbee/drone-kubernetes
        kubernetes_server: ${KUBERNETES_SERVER}
        kubernetes_cert: ${KUBERNETES_CERT}
        kubernetes_token: ${KUBERNETES_TOKEN}
        deployment: medzoner
        repo: medzoner/medzoner.com
        container: medzoner-nginx
        tag:
            - ${DRONE_COMMIT_SHA:0:8}