pipeline:

    deployer-build:
        image: plugins/docker
        group: deployer # parallel
        repo: registry.medzoner.com/medzoner/deployer
        dockerfile: DockerfileDeploy
        secrets: [ docker_username, docker_password ]
        registry: registry.medzoner.com
        debug: true
        tags:
            - latest
            - ${DRONE_COMMIT_SHA:0:8}

    app-test:
        image: medzoner/medzoner_php
        group: test # parallel
        commands:
          - apt-get update
          - apt-get install -y --force-yes nginx curl
          - composer install
          - ./bin/phpunit -c app
          - rm -rf ./vendor
          - composer install -n --no-dev --optimize-autoloader --no-progress

    cdn-test:
        image: node
        group: test # parallel
        commands:
          - npm install
          - npm install -g bower karma gulp
          - gulp

    app-build:
        image: plugins/docker
        group: build # parallel
        repo: registry.medzoner.com/medzoner/medzoner.com
        dockerfile: Dockerfile
        secrets: [ docker_username, docker_password ]
        registry: registry.medzoner.com
        debug: true
        tags:
            - latest
            - ${DRONE_COMMIT_SHA:0:8}

    cdn-build:
        image: plugins/docker
        group: build # parallel
        repo: registry.medzoner.com/medzoner/cdn.medzoner.com
        dockerfile: DockerfileCdn
        secrets: [ docker_username, docker_password ]
        registry: registry.medzoner.com
        debug: true
        tags:
            - latest
            - ${DRONE_COMMIT_SHA:0:8}

    app-deploy:
        image: registry.medzoner.com/medzoner/deployer
        secrets: [ docker_username, docker_password, kube_config ]
        group: deploy # parallel
        commands:
          - echo $KUBE_CONFIG | base64 -d > /tmp/admin.conf # Add secret with: cat admin.conf | base64 && cat admin.conf.base64 | base64 -d
          - export KUBECONFIG=/tmp/admin.conf
          #- kubectl -n default set image deployment/medzoner-php medzoner-php=registry.medzoner.com/medzoner/medzoner.com:${DRONE_COMMIT_SHA:0:8}
          - kubectl patch deployment/medzoner-php --patch "{\"spec\": {\"template\": {\"spec\": {\"initContainers\": [{\"name\": \"code\",\"image\": \"registry.medzoner.com/medzoner/medzoner.com\"}]}}}}:${DRONE_COMMIT_SHA:0:8}"

    cdn-deploy:
        image: registry.medzoner.com/medzoner/deployer
        secrets: [ docker_username, docker_password, kube_config ]
        group: deploy # parallel
        commands:
          - echo $KUBE_CONFIG | base64 -d > /tmp/admin.conf # Add secret with: cat admin.conf | base64 && cat admin.conf.base64 | base64 -d
          - export KUBECONFIG=/tmp/admin.conf
          - kubectl -n default set image deployment/medzoner-cdn medzoner-cdn=registry.medzoner.com/medzoner/cdn.medzoner.com:${DRONE_COMMIT_SHA:0:8}

