pipeline:
    cdn:
        image: node
        group: build # parallel
        commands:
          - npm install
          - npm install -g bower karma gulp
          - gulp

    app:
        image: medzoner/medzoner_php
        group: build # parallel
        commands:
          - apt-get update
          - apt-get install -y --force-yes nginx curl
          - composer install
          - ./bin/phpunit -c app
          - rm -rf ./vendor
          - composer install -n --no-dev --optimize-autoloader --no-progress

    cdn-build:
        image: plugins/docker
        repo: registry.medzoner.com/medzoner/cdn.medzoner.com
        dockerfile: DockerfileCdn

    app-build:
        image: plugins/docker
        repo: registry.medzoner.com/medzoner/medzoner.com
        dockerfile: Dockerfile

    deploy:
        image: quay.io/honestbee/drone-kubernetes
        kubernetes_server: ${KUBERNETES_SERVER}
        kubernetes_cert: ${KUBERNETES_CERT}
        kubernetes_token: ${KUBERNETES_TOKEN}
        deployment: medzoner
        repo: medzoner/medzoner.com
        container: medzoner-nginx
        tag:
            - ${DRONE_COMMIT_SHA:0:8}