---
kind: pipeline
name: default

steps:
  - name: app-test
    image: medzoner/medzoner_php
    commands:
      - apt-get update
      - apt-get install -y --force-yes nginx curl
      - composer install
      - ./bin/phpunit -c app
    when:
      branch:
        - master
        - staging
        - development

  - name: cdn-test
    image: node:7
    commands:
      - npm install
      - npm install -g bower karma gulp
      - gulp
    when:
      branch:
        - master
        - staging
        - development

  - name: app-build
    image: plugins/docker
    repo: l24624j7.gra5.container-registry.ovh.net/medzoner/medzoner.com
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    registry: l24624j7.gra5.container-registry.ovh.net
    debug: true
    tags:
        - latest
        - ${DRONE_COMMIT_SHA}
    when:
      branch:
        - master
        - staging
        - development

  - name: "tag config repo"
    image: ubuntu
    environment:
      SSH_KEY:
        from_secret: ssh_key
      TAG_REPO:
        from_secret: tag_repo
    volumes:
      - name: key
        path: /root/.ssh
    commands:
      - apt-get -yq update && apt-get -yqq install ssh git
      - echo $SSH_KEY | base64 -d > /root/.ssh/id_rsa
      - echo $SSH_KEY | base64 -d > /root/private_key
      - chmod 600 /root/.ssh/id_rsa
      - touch /root/.ssh/known_hosts
      - ssh-keyscan bitbucket.org >> /root/.ssh/known_hosts
      - git config --global user.email "pipeline@medzoner.com" && git config --global user.name "pipeline"
      - cd /tmp && git clone $TAG_REPO && cd medzoner-gitops
      - ./tag_repo.sh
    when:
      branch:
        - master
        - staging
        - development
