---
kind: pipeline
name: default

steps:
  - name: unit-test
    image: medzoner/medzoner_php
    commands:
      - 'cp -f ./config/parameters.yml.dist ./config/parameters.yml'
      - composer install
      - ./bin/phpunit -c phpunit.xml.dist
    when:
      branch:
        - master
        - staging
        - development

  - name: build-assets
    image: node:10.3.0
    commands:
      - /usr/local/bin/bower install --allow-root
      - /usr/local/bin/gulp
    when:
      branch:
        - master
        - staging
        - development

  - name: image-build
    image: plugins/docker
    debug: true
    settings:
      repo: l24624j7.gra5.container-registry.ovh.net/medzoner/medzoner.com
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      registry: l24624j7.gra5.container-registry.ovh.net
      tags:
          - latest
          - ${DRONE_COMMIT_SHA}
    when:
      branch:
        - master
        - staging
        - development

  - name: "tag config repo"
    image: medzoner/pipeline
    environment:
      SSH_KEY:
        from_secret: ssh_key
      TAG_REPO:
        from_secret: tag_repo
    volumes:
      - name: key
        path: /root/.ssh
    commands:
      - echo $SSH_KEY | base64 -d > /root/.ssh/id_rsa
      - echo $SSH_KEY | base64 -d > /root/private_key
      - chmod 600 /root/.ssh/id_rsa
      - cd /tmp && git clone $TAG_REPO && cd medzoner-gitops
      - ./tag_repo.sh medzoner
    when:
      branch:
        - master
        - staging
        - development
