pipeline:
    cdn:
        image: node
        commands:
          - npm install && npm install -g bower karma gulp && gulp && composer install -n --no-dev --optimize-autoloader --no-progress && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && bash deploy.sh 1.0

    app:
        image: php:7.1
        commands:
          - apt-get update
          - apt-get install -y --force-yes nginx curl
          - composer install -n --no-dev --optimize-autoloader --no-progress
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - bash deploy.sh 1.0
          - ./bin/phpunit -c app

    deploy:
        image: quay.io/honestbee/drone-kubernetes
        kubernetes_server: ${KUBERNETES_SERVER}
        kubernetes_cert: ${KUBERNETES_CERT}
        kubernetes_token: ${KUBERNETES_TOKEN}
        deployment: medzoner
        repo: medzoner/medzoner.com
        container: medzoner-nginx
        tag:
            - ${DRONE_COMMIT_SHA:0:8}