pipeline:

    app-test:
        image: medzoner/medzoner_php
        group: test # parallel
        commands:
          - apt-get update
          - apt-get install -y --force-yes nginx curl
          - composer install
          - ./bin/phpunit -c app
          - rm -rf ./vendor
          - composer install -n --no-dev --optimize-autoloader --no-progress

    cdn-test:
        image: node
        group: test # parallel
        commands:
          - npm install
          - npm install -g bower karma gulp
          - gulp

    app-build:
        image: plugins/docker
        group: build # parallel
        repo: registry.medzoner.com/medzoner/medzoner.com
        dockerfile: Dockerfile
        secrets: [ docker_username, docker_password ]
        registry: registry.medzoner.com
        debug: true
        tags:
            - latest
            - ${DRONE_COMMIT_SHA}
