build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: cp -f ./.env.test ./.env && ./bin/phpunit -c phpunit.xml.dist --coverage-clover=build/coverage.xml
            use_website_config: true
            coverage:
              file: build/coverage.xml
              format: clover
    tests: true
filter:
  excluded_paths:
    - 'tests/*'

checks:
  php: true

coding_style:
  php:
    spaces:
      other:
        after_type_cast: false

tools:
  external_code_coverage:
    timeout: 600
    runs: 1
