language: php

php:
    - 7.1

services:
    - docker

before_install:
    - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - docker pull medzoner/medzoner.com
    - docker run -d medzoner/medzoner.com
    - docker ps -a
before_script:
    - composer install -n
    - sudo apt-get update > /dev/null
    - sudo apt-get install -y --force-yes nginx

script:
    - ./bin/phpunit -c app
    #- ./bin/behat

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

env:
  global:
    secure: kkYrOtLfCMc6je5D+P94EswYUCC++VJKEttcjhERUqG2cW1iInkXd3DVzO0ZLo7CV7u9vW2BA8AssfxWstBYFaO2CHQZXQJRAs2OeK3MtiofAhVbX+KrqjtVG55JBxk/f57CnnPFeniwm2LrcLRGyV746jNS4mfT6+4PDejlltf9uIIIhfQeF4gzZK6xmI3ZqhnIe21QtzYyLYIoGHzZ1PU2j1CVCrg1zpvVWfQNi9bCOGRZzzq0kmdP7xD3ua0Nb0wfJj7GKjw9cLxySqbE+tnRCjaR0kPAzCeNc2WIVfgpFrWg9vSuC3bs0hKpKI0wAdrYC+bQWuHsA3HRnisxQcsbWx29USacpW0EUEgMpjRJSh8LFL7syFni9KXpgnEuTlVGD5hQvmFdx0EK/L6frbMFDHXTxyHKb8f546+J5g6yW+xT9/FEMcbWSCFCZcXaN/YXsNKqRdDKEWq18jZqgWkYMY2s87PPfljr9y3+l8JiputLpSkSFJQUWtXlEIQCPYokf5nuq+BG0CGigerN+jdGwkt8TZxQUfkeueHl+C5d6Jq3aTq74NAS/nqoic94tAGfJQo5IL/VFeQH53hOisMTK7xFQzWvkMi72WmzA+rNo8YHhWiLCPS+26j+1O83BO7KUAwBUI1n7pGrB5/k3jJnPLL9YRiYz5S7nsMn1QM=

after_success:
  - "openssl aes-256-cbc -k $DEPLOY_KEY -in config/deploy_id_rsa_enc_travis -d -a -out config/deploy_id_rsa"
  - "[[ $TRAVIS_BRANCH = 'master' ]] && bundle exec cap production deploy"