language: php

php:
  - 7.1

env:
  - NODE_RELEASE=10.x

services:
  - docker

install:
  - 'cp -f ./config/parameters.yml.dist ./config/parameters.yml'
  - composer install -n

script:
  - ./bin/phpunit -c phpunit.xml.dist
