version: '3'

services:
    portainer:
        image: "portainer/portainer"
        container_name: "medzoner-portainer"
        restart: "no"
        ports:
            - "9999:9000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./var/portainer-data:/data"

    db:
        image: "mariadb"
        container_name: "medzoner-mariadb"
        hostname: "medzoner-mariadb"
        restart: "no"
        user: "1000:1000"
        environment:
            MYSQL_ROOT_PASSWORD: "toor"
        ports:
            - "3306:3306"
        #volumes:
        #    - './var/mariadb:/var/lib/mysql'
        networks:
            - "default"

    #mongo
    mongo-medzoner:
        image: "mongo"
        container_name: "mongo-medzoner"
        restart: "always"
        networks:
            - "default"

    #nginx
    nginx:
        image: "nginx:1.11"
        container_name: "medzoner-nginx"
        hostname: "medzoner-nginx"
        depends_on:
            - "php"
        restart: "no"
        ports:
            - "80:80"
        environment:
            USER_UID: "1000"
            USER_GID: "1000"
            PHP_HOST: "medzoner-php"
        networks:
            - "default"
        volumes:
            - "medzoner:/var/www"
            - './etc/nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf'
            - './etc/nginx/nginx.conf:/etc/nginx/nginx.conf'

    php:
        image: "medzoner/medzoner_php"
        container_name: "medzoner-php"
        restart: "no"
        working_dir: "/var/www"
        depends_on:
            - "db"
        volumes:
            - "medzoner:/var/www"
        networks:
            - "default"

##networks
networks:
  default:
    driver: "bridge"

volumes:
    db: {}
    medzoner:
      driver_opts:
        type: none
        device: $PWD
        o: bind
