version: '2'
services:
  php:
    extends:
      file: "./docker-files/docker-compose.yml"
      service: php

  nginx:
    extends:
      file: "./docker-files/docker-compose.yml"
      service: nginx
