version: '2'

services:
    #php
    php-medzoner:
        build: "./docker/php"
        container_name: "php-medzoner"
        working_dir: "${PATHBASE}"
        restart: "always"
        environment:
          USER_UID: "${USER_UID}"
          USER_GID: "${USER_GID}"
          XDEBUG_CONFIG: "remote_host=${XDEBUG_CONFIG_HOST} remote_port=${XDEBUG_CONFIG_PORT}"
          PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG}"
        volumes:
            - "${PATH_PROJECT}:/var/www/medzoner"
            # ssh git auth
            - "$SSH_AUTH_SOCK:/ssh-agent"
            - "~/.ssh/id_rsa:/home/www-data/private_key"
            # bitbucket auth
            - "${HOME_PATH}/.ssh:/home/www-data/.ssh"
            - "${HOME_PATH}/.composer:/home/www-data/.composer"
            # php conf by env
            - "./etc/php/7.0/php.prod.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/php/7.0/xdebug.prod.ini:/usr/local/etc/php/conf.d/xdebug.ini"
            - "./etc/php/7.0/php-fpm.d/docker.conf:/usr/local/etc/php-fpm.d/docker.conf"
        networks:
          medzoner:
            aliases:
              - "php-medzoner"
        extra_hosts:
         - "medzoner.dev:172.19.0.1"

    #nginx
    nginx-medzoner:
        image: "medzoner/medzoner_nginx"
        container_name: "nginx-medzoner"
        working_dir: "${PATHBASE}"
        restart: "always"
        ports:
            - "9061:80"
        volumes:
            - "${PATH_PROJECT}:/var/www/medzoner"
            # nginx vhost by env
            - "./etc/nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
        networks:
          medzoner:
            aliases:
              - "nginx-medzoner"

networks:
    medzoner:
        driver: "bridge"
volumes:
    db: {}
