version: '2'
services:
  php-medzoner:
    extends:
      file: "./docker-files/docker-compose.yml"
      service: php

  nginx-medzoner:
    extends:
      file: "./docker-files/docker-compose.yml"
      service: nginx
    links:
        - "php-medzoner"
