version: '2'

services:
    #capistrano
    capistrano-medzoner:
        image: "medzoner/medzoner_capistrano"
        container_name: "capistrano-medzoner"
        working_dir: "/source"
        restart: "always"
        volumes:
            - "${PATHBASE}:/source"
            - "${HOME_PATH}/.ssh:/root/.ssh"
            # bitbucket auth
            - "${HOME_PATH}/.ssh:/home/www-data/.ssh"
        networks:
          medzoner:
            aliases:
              - "capistrano-medzoner"
        command: 'cap -v'

networks:
    medzoner:
        driver: "bridge"
        ipam:
            driver: "default"
            config:
                - subnet: "172.61.0.0/24"
                  gateway: "172.61.0.1"
volumes:
    db: {}
