liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        blog_thumb:
            quality: 100
            filters:
                thumbnail: { size: [178, 134], mode: outbound }
