imports:
    - { resource: config.yml }
    # Framework - monolog
    - { resource: framework/monolog.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
