imports:
    # Framework - framework
    - { resource: framework/framework.yml }
    # Framework - twig
    - { resource: framework/twig.yml }
    # Framework - assetic
    - { resource: framework/assetic.yml }
    # Framework - doctrine
    - { resource: framework/doctrine.yml }
    # Framework - swiftmailer
    - { resource: framework/swiftmailer.yml }

    # Parameters
    - { resource: parameters.yml }
    # Security
    - { resource: security.yml }

    # Bundles - Fos Elastica
    #- { resource: bundles/fos_elastica.yml }
    # Bundles - Fos User
    - { resource: bundles/fos_user.yml }
    # Bundles - Knp Menu
    - { resource: bundles/knp_menu.yml }
    # Bundles - Liip Imagine
    - { resource: bundles/liip_imagine.yml }
