imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        collect: true

web_profiler:
    toolbar: true
    intercept_redirects: false

#swiftmailer:
#    delivery_address: medzoner@gmail.com
