imports:
    # Framework - framework
    - { resource: framework/framework.yml }
    # Framework - twig
    - { resource: framework/twig.yml }
    # Framework - doctrine
    - { resource: framework/doctrine.yml }
    # Framework - swiftmailer
    - { resource: framework/swiftmailer.yml }
    # Framework - monolog
    - { resource: framework/monolog.yml }

    # Parameters
    - { resource: parameters.yml }
    # Security
    - { resource: security.yml }

    # Bundles - Knp Menu
    - { resource: bundles/knp_menu.yml }
    # Bundles - Liip Imagine
    - { resource: bundles/liip_imagine.yml }

