medzoner_global_index:
    resource: "@MedzonerGlobalBundle/Resources/config/routing.yml"
    prefix:   /

medzoner_api_index:
    resource: "@MedzonerApiBundle/Resources/config/routing.yml"
    prefix:   /api
    
##########################################################################
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
