# Home
site:
    path:  /
    defaults: { _controller: 'medzoner.home.controller:indexAction' }

site_home:
    path:  /home
    defaults: { _controller: 'medzoner.home.controller:indexAction' }

# Contact
site_contact:
    path:  /contact
    defaults: { _controller: 'medzoner.contact.controller:contactAction' }

# Portfolio
site_book:
    path:  /book
    defaults: { _controller: 'MedzonerGlobalBundle:Portfolio:index' }

# CV
site_cv:
    path: /cv
    defaults: { _controller: 'medzoner.jobboard.controller:indexAction' }

# Foundation
site_foundation:
    path:  /foundation
    defaults: { _controller: 'MedzonerGlobalBundle:Foundation:index' }

# Proxy
site_pages_proxy:
    path:  /proxy
    defaults: { _controller: 'MedzonerGlobalBundle:Proxy:index' }

site_pages_proxy_url:
    path:  /proxy/{url}
    defaults: { _controller: 'MedzonerGlobalBundle:Proxy:index' }



#=============================== Cache ===============================
site_cache:
    path:     "/cache"
    defaults: { _controller: "medzoner.cache.query.controller:indexAction" }
