# Home
site:
    path:  /
    defaults: { _controller: 'Medzoner\GlobalBundle\Controller\IndexController:indexAction', _format: "html" }

site_home:
    path:  /home
    defaults: { _controller: 'Medzoner\GlobalBundle\Controller\IndexController:indexAction', _format: "html" }

# Contact
site_contact:
    path:  /contact
    defaults: { _controller: 'Medzoner\GlobalBundle\Controller\ContactController:contactAction', _format: "html" }

# Technos
site_technos:
    path: /technos
    defaults: { _controller: 'Medzoner\GlobalBundle\Controller\TechnosController:indexAction', _format: "html" }


