services:
  medzoner.jobboard.service:
    class: 'Medzoner\GlobalBundle\Services\JobBoardService'
    arguments:
        - '@medzoner.jobboard.model'

  medzoner.jobboard.model:
    class: 'Medzoner\GlobalBundle\Model\JobBoard'
