services:
  medzoner.jobboard.service:
    class: 'Medzoner\GlobalBundle\Services\JobBoardService'
    arguments:
        - '@medzoner.jobboard.provider'

  medzoner.jobboard.model:
    class: 'Medzoner\GlobalBundle\Model\JobBoard'

  medzoner.jobboard.content.model:
    class: 'Medzoner\GlobalBundle\Model\JobBoardContent'

  medzoner.jobboard.provider:
    class: 'Medzoner\GlobalBundle\Provider\JobBoard\JobBoardProvider'
