version: '2'

services:
  #composer
  composer:
    build: "./docker-files/docker-composer"
    container_name: "medzoner-composer-${PROJECT_UID}"
    working_dir: "/var/www/medzoner/current"
    volumes:
      - "/var/www:/var/www"
      # ssh git auth
      - "$SSH_AUTH_SOCK:/ssh-agent"
      - "/root/.ssh/id_rsa:/home/www-data/private_key"
      # bitbucket auth
      - "/root/.ssh:/home/www-data/.ssh"
      - "/root/.composer:/home/www-data/.composer"
    environment:
        USER_UID: "${USER_UID}"
        USER_GID: "${USER_GID}"
        SSH_AUTH_SOCK: "${SSH_AUTH_SOCK}"
