# Home
api:
    path:  /
    defaults: { _controller: 'medzoner.api.home.controller:indexAction' }

# Contact
api_contact:
    path:  /contact
    defaults: { _controller: 'medzoner.api.contact.controller:contactAction' }

# Contact
api_contact_search:
    path:  /contact/search
    defaults: { _controller: 'medzoner.api.contact.controller:searchAction' }
