# Doctrine Configuration
doctrine:
    dbal:
        driver:   '%env(string:DB_DRIVER)%'
        host:     '%env(string:DB_HOST)%'
        port:     '%env(string:DB_PORT)%'
        dbname:   '%env(string:DB_DATABASE)%'
        user:     '%env(string:DB_USER)%'
        password: '%env(string:DB_PASSWORD)%'
        charset:  'UTF8'
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Doctrine Migration Configuration
#doctrine_migrations:
#    dir_name: '%kernel.root_dir%/DoctrineMigrations'
#    namespace: Application\Migrations
#    table_name: migration_versions
#    name: Application Migrations

# Doctrine Mongodb Configuration
#doctrine_mongodb:
#    connections:
#        default:
#            server: '%mongo_database_dsn%'
#            options: {}
#    default_database: 'medzoner'
#    document_managers:
#        default:
#           auto_mapping: true
