framework:
    #esi:             ~
    translator:      { fallback: '%env(string:locale)%' }
    secret:          '%env(string:secret)%'
    router:
        resource: "%kernel.root_dir%/../config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: true
    validation:      { enable_annotations: true }
        #assets_version: SomeVersionScheme
    default_locale:  '%env(string:locale)%'
    trusted_hosts:   ~
    #trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    http_method_override: true

    esi:       { enabled: true }
    fragments: { path: /_fragment }
