monolog:
    handlers:
        main:
            type:             'fingers_crossed'
            action_level:            'debug'
            handler: 'grouped'
            channels: ['!event']

        grouped:
            type:    'group'
            members: ['nested', 'buffered', 'outputted']

        nested:
            type: 'stream'
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: 'debug'

        outputted:
            type: 'stream'
            path: 'php://stdout'
            level: 'debug'

        buffered:
            type:    'buffer'
            handler: 'swift'

        swift:
            type: 'swift_mailer'
            from_email: '%env(string:monolog_mail)%'
            to_email: '%env(string:monolog_mail)%'
            subject: "[medzoner.com %env(string:branch)%] Fatal Error!"
            level: 'critical'

        redis:
            type:  'service'
            id:    'snc_redis.monolog.handler'
            level: 'debug'
