# Swiftmailer Configuration
swiftmailer:
    default_mailer: 'default'
    mailers:
        default:
            transport: "%mailer_transport%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            #encryption: "tls"
            #port:       "587"
            #encryption: "%mailer_encryption%"
            #port:       "%mailer_port%"
            spool:
                type: 'service'
                id: 'snc_redis.swiftmailer.spool'