# Swiftmailer Configuration
swiftmailer:
    default_mailer: 'default'
    mailers:
        default:
            transport: "%env(string:mailer_transport)%"
            host:      "%env(string:mailer_host)%"
            username:  "%env(string:mailer_user)%"
            password:  "%env(string:mailer_password)%"
            #encryption: "tls"
            #port:       "587"
            #encryption: "%env(string:mailer_encryption)%"
            #port:       "%env(string:mailer_port)%"
            spool:
                type: 'service'
                id: 'snc_redis.swiftmailer.spool'
