# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    globals:
        medzoner_cdn_url: '%env(string:medzoner_cdn_url)%'
        advert_script: '%env(string:advert_script)%'
