# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    globals:
        medzoner_cdn_url: '%medzoner_cdn_url%'
        advert_script: '%advert_script%'
