site_blog_homepage:
    path:  /blog
    defaults: { _controller: SiteBlogBundle:Index:index }

site_blog_show:
    path:  /blog/{id}/{slug}/{comments}
    defaults: { _controller: SiteBlogBundle:Index:show, comments: true }
    requirements:
        id: \d+
    methods:  [GET]
        
site_blog_page:
    path:  /blog/page/{page}
    defaults: { _controller: SiteBlogBundle:Index:list, page: 1 }

site_blog_sidebar:
    path:  /sidebar
    defaults: { _controller: SiteBlogBundle:Index:sidebar }
    methods:  [GET]
        
site_blog_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: SiteBlogBundle:Comment:create }
    requirements:
        blog_id: \d+
    methods:  [POST]


        
site_blog_new:
    path:  /blog/new
    defaults: { _controller: SiteBlogBundle:Blog:new }
    methods:  [GET]

site_blog_create:
    path:  /blog/create
    defaults: { _controller: SiteBlogBundle:Blog:create }
    requirements:
        blog_id: \d+
    methods:  [POST]