site_foundation:
    pattern:  /foundation
    defaults: { _controller: SitePagesBundle:Foundation:index }
    
site_pages_proxy:
    pattern:  /proxy
    defaults: { _controller: SitePagesBundle:Proxy:index }
    
site_pages_proxy_url:
    pattern:  /proxy/{url}
    defaults: { _controller: SitePagesBundle:Proxy:index }

#site_search:
#    path: /search
#    defaults: { _controller: SitePagesBundle:Search:index }